### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by dackid19** [Villfuk02/The-Marksman#1]
I do like where the marksman is heading. I do hope you can fix the art, even using old art with a different color scheme will do. I would also recommend making the character start at 3 energy. These may be just preferences, but I think it will help polish the character more.

**Comment by Villfuk02** [comment]
I won't change the characer to 3 energy. It is built around having 4.
I plan on fixing the art, but I'll fix the gameplay first.

**Comment by dackid19** [comment]
Playing more with your character, I completely understand why it has 4 energy. And it does make sense. You have a good character in the works. I wish you the best on it.
