### ISSUE TITLE
Game crashes when you raise ascension level

### ISSUE THREAD

**Issue by Conman5534** [Villfuk02/The-Marksman#10]
I am experiencing a problem where if you go into the custom game thing and raise the ascension level, the crashes. Also, when you look for what closed the game, it says game closed.

Here is the crash log: [https://pastebin.com/Q0Xd9rv0](https://pastebin.com/Q0Xd9rv0)
(or at least some of it. I was playing for a while)

**Comment by Villfuk02** [comment]
Does it crash without The Marksman?
