### ISSUE TITLE
Trusty magazine whithout unlocks

### ISSUE THREAD

**Issue by 5m1l35** [Villfuk02/The-Marksman#11]
If you have not finished unlocking and you get the trusty magazine relic you just lose the rusty handguns and don't receive the trusty handguns. at least that is what appears to happen

**Comment by 5m1l35** [comment]
correction trusty magazine is currently broken I believe

**Comment by Villfuk02** [comment]
please provide more info, I'm currently unable to replicate the bug.

**Comment by 5m1l35** [comment]
Its possible it is a problem of combining to many mods on my end I am no
the beta branch and have like ten other class mods so if you are not having
the issue I imagine one of those is the issue.

**Comment by DanielRewcastle** [comment]
Nope it was definitely busted on my first run I got the trusty magazine relic and it just removed the rusty handguns and didn't give me the trusty handguns.

**Comment by Villfuk02** [comment]
s h o u l d    be fixed now
