### ISSUE TITLE
void grenade crashing the game

### ISSUE THREAD

**Issue by 5m1l35** [Villfuk02/The-Marksman#5]
So did you intend for void grenade to crash the game occasionally.Which it kinda of seems like with the warning. If so could you tell me the criteria or is it random chance.

**Comment by 5m1l35** [comment]
If you did not then I think it has to do with the large animations and that you gave the grenades and the fact that it seems to play them almost simultaneously. Or I am totally miss understanding I also noticed a trend, with having multiple grenades in hand besides the void when I played it and it triggering a crash.

**Comment by Villfuk02** [comment]
please post the crash log when that happens again
