### ISSUE TITLE
Eh... This card.

### ISSUE THREAD

**Issue by SirUmnei** [Villfuk02/The-Marksman#9]
Having MadScience Mod on seems to be conflicting with one of the cards.
![image](https://user-images.githubusercontent.com/13974621/43994662-2e37fc08-9d77-11e8-936a-e951beed9bff.png)

**Comment by Villfuk02** [comment]
contacted the madsciencemod author

**Comment by SilentJ28** [comment]
They fixed this in their latest release: https://github.com/twanvl/sts-mad-science-mod/releases/tag/v0.2.1
